name: Deploy to GitHub Pages

on:
  push:
    branches: [ feature/dash-lambda ]
  workflow_dispatch: {}

permissions:
  contents: write
  pages: write
  id-token: write

defaults:
  run:
    working-directory: dashboard

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: dashboard/pnpm-lock.yaml

      # EITHER use the pnpm action…
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      # …OR use Corepack instead (remove the action above if you use this)
      # - name: Enable pnpm via Corepack
      #   run: |
      #     corepack enable
      #     corepack prepare pnpm@9 --activate

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build static site
        env:
          NODE_ENV: production
          GH_PAGES: "true"
        run: pnpm build  # writes ./dashboard/out

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dashboard/out
          publish_branch: gh-pages
