name: Deploy to GitHub Pages

on:
  push:
    branches: [ feature/dash-lambda ]
  workflow_dispatch: {}

permissions:
  contents: write
  pages: write
  id-token: write

# 👇 All `run:` commands execute inside ./dashboard
defaults:
  run:
    working-directory: dashboard

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          # cache lockfile in the subfolder
          cache-dependency-path: dashboard/pnpm-lock.yaml

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build static site
        env:
          NODE_ENV: production
        run: pnpm build   # -> writes ./dashboard/out because Next output:'export'

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dashboard/out     # 👈 path relative to repo root
          publish_branch: gh-pages
