name: Deploy to GitHub Pages

on:
  push:
    branches: [ feature/dash-lambda ]
  workflow_dispatch: {}

permissions:
  contents: write
  pages: write
  id-token: write

defaults:
  run:
    working-directory: dashboard

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: '9'   # 👈 Add this — make sure it's a string
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: dashboard/pnpm-lock.yaml  # 👈 tell GitHub where to find it

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build static site
        env:
          NODE_ENV: production
          GH_PAGES: "true"
        run: pnpm build

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dashboard/out
          publish_branch: gh-pages
